import type { SupportedLanguage } from '../../../i18n'

const zhCN = {
  heroTitle: '选择导演台，继续完成场景',
  heroDescription: '每个导演台独立保存。进入后可以继续布置角色、道具、机位和运镜路线。',
  deskLabel: '导演台',
  scrollHint: '查看使用说明',
  myDesks: '我的导演台',
  deskCount: (count: number) => `共 ${count} 个导演台`,
  createDesk: '新建导演台',
  deskListAria: '导演台列表',
  deleteDeskAria: (name: string) => `删除${name}`,
  emptyListAria: '空导演台列表',
  emptyTitle: '还没有导演台',
  emptyDescription: '新建一个导演台，从空场景开始。',
  paginationAria: '导演台分页',
  previousPage: '上一页',
  nextPage: '下一页',
  quickStartBadge: '第一次使用',
  quickStartTitle: '四步完成第一条运镜',
  quickStartDescription: '不用先学习复杂的 3D 软件，按照下面顺序操作即可。',
  quickStartSteps: [
    ['选择导演台', '打开已有导演台，或点击“新建导演台”创建一个空场景。'],
    ['摆人物和道具', '从工具栏添加模型，选中后使用 XYZ 三轴移动、旋转和缩放。'],
    ['记录镜头', '点击“运镜 → 开始掌镜”，用 WASD 移动，每到一个镜头按 Enter。'],
    ['预演并导出', '先“看路线”检查轨迹，再“看成片”，满意后导出 MP4 参考视频。'],
  ],
  cameraShortcuts: '掌镜快捷键',
  move: '移动',
  descendAscend: '下降 / 上升',
  saveShot: '保存镜头',
  playPause: '播放 / 暂停',
  exitCamera: '退出掌镜',
  releaseBadge: '本次更新',
  releaseTitle: '路线编辑、监看与导出升级',
  releaseDescription: '这次重点补全人物运动、镜头预演和参考视频工作流。',
  releaseNotes: [
    '人物路线支持添加、插入、删除和拖动，行走时会沿平滑曲线自然转向',
    '人物路线与摄影机轨迹可常亮显示，并支持批量移动多个轨迹点',
    '新增路径碰撞开关，可让人物贴地，并阻止人物和镜头穿过场景物体',
    '看成片时可随时暂停和拖动底部时间轴，不会再退出第一视角预览',
    '主成片 FOV 与监看小窗 FOV 已分开设置，导出使用主成片 FOV',
    '新增可拖动实时监看小窗、MP4 参考视频导出和更可靠的撤销逻辑',
  ],
  controlsBadge: '完整操作表',
  controlsTitle: '键盘、鼠标与触控板操作',
  controlsDescription: '快捷键在输入框中不会触发；掌镜模式下请先单击 3D 画面锁定鼠标。',
  controlGroups: [
    {
      title: '普通导演视角',
      description: '摆场景和检查路线时使用',
      controls: [
        ['W / A / S / D', '前进、左移、后退、右移'],
        ['Space / Shift', '上升 / 下降'],
        ['鼠标左键拖动', '环绕观察场景'],
        ['鼠标右键拖动', '平移观察中心'],
        ['滚轮', '靠近 / 远离场景'],
      ],
    },
    {
      title: '掌镜模式',
      description: '像 FPS 游戏一样录制摄影机轨迹点',
      controls: [
        ['W / A / S / D', '前进、左移、后退、右移'],
        ['E / Q', '镜头上升 / 下降'],
        ['移动鼠标', '转动镜头方向'],
        ['Enter', '保存或更新当前轨迹点'],
        ['Space', '播放 / 暂停人物和物体运动'],
        ['F', '锁定或取消准星所指目标'],
        ['滚轮', '调整镜头 FOV'],
        ['Esc', '释放鼠标并退出掌镜'],
        ['单击画面', '重新锁定鼠标'],
      ],
    },
    {
      title: '通用编辑',
      description: '场景、路线点和时间轴都适用',
      controls: [
        ['⌘ / Ctrl + C', '复制选中的人物或物体'],
        ['⌘ / Ctrl + V', '粘贴并选中新副本'],
        ['⌘ / Ctrl + Z', '撤销最近一次编辑或拖动'],
        ['Shift + 单击', '在场景树中多选 / 取消选择'],
        ['Delete / Backspace', '删除当前选中对象'],
        ['拖动 XYZ 字母', '连续调整对应轴数值'],
        ['↑ / ↓', '聚焦 XYZ 字母时微调数值'],
        ['拖动底部时间轴', '立即暂停并定位到指定时间'],
      ],
    },
  ],
  macTitle: 'macOS 触控板手势',
  macDescription: '以 MacBook 默认手势和已开启“辅助点按”为准',
  macGestures: [
    ['单指按下并拖动', '普通导演视角中环绕观察；掌镜时直接移动手指即可转向'],
    ['双指上下滑动', '普通视角缩放场景；掌镜模式调整镜头 FOV'],
    ['双指点按后拖动', '开启 macOS“辅助点按”后，可平移普通导演视角'],
    ['双指滚动首页', '上下查看完整使用说明和本次更新'],
    ['轻点画面', '掌镜退出锁定后，重新进入鼠标锁定'],
  ],
  toolsTitle: '主要界面按钮',
  toolGroups: [
    ['顶部', '首页、切换导演台、导演/第一视角、运镜工作台、视角手感'],
    ['视口工具栏', '移动、旋转、缩放、添加角色、路线常亮、导入模型、模型库、添加机位'],
    ['画面工具', '选择画幅、当前/四方位/十二方位截图、全屏'],
    ['底部时间轴', '回到开头、播放/暂停、拖动定位、总时长、记录点、删除当前点'],
    ['运镜工作台', '开始掌镜、添加/插入/批量移动轨迹点、看路线、看成片、导出视频'],
    ['右侧属性', '对象 XYZ、姿势、动作、人物路线、场景地面与路径碰撞'],
  ],
  deleteTitle: '删除这个导演台？',
  deleteDescription: (name: string) => `“${name}”及其中本地保存的场景数据将被永久删除，此操作无法撤销。`,
  cancel: '取消',
  delete: '删除',
  home: '首页',
  backHome: '返回首页',
  deskSelector: '导演台选择器',
  selectDesk: '选择导演台',
  create: '新建',
  justUpdated: '刚刚更新',
  minutesAgo: (value: number) => `${value} 分钟前`,
  hoursAgo: (value: number) => `${value} 小时前`,
} as const

const enUS = {
  heroTitle: 'Choose a director desk and continue your scene',
  heroDescription: 'Each desk is saved independently, so you can continue arranging characters, props, cameras, and camera paths.',
  deskLabel: 'Director desks',
  scrollHint: 'View guide',
  myDesks: 'My director desks',
  deskCount: (count: number) => `${count} director ${count === 1 ? 'desk' : 'desks'}`,
  createDesk: 'New director desk',
  deskListAria: 'Director desk list',
  deleteDeskAria: (name: string) => `Delete ${name}`,
  emptyListAria: 'Empty director desk list',
  emptyTitle: 'No director desks yet',
  emptyDescription: 'Create a director desk and start with an empty scene.',
  paginationAria: 'Director desk pagination',
  previousPage: 'Previous page',
  nextPage: 'Next page',
  quickStartBadge: 'Getting started',
  quickStartTitle: 'Create your first camera move in four steps',
  quickStartDescription: 'You do not need to learn complex 3D software first. Just follow these steps.',
  quickStartSteps: [
    ['Choose a desk', 'Open an existing desk, or select “New director desk” to create an empty scene.'],
    ['Place characters and props', 'Add models from the toolbar, then use the XYZ axes to move, rotate, and scale them.'],
    ['Record camera points', 'Open Camera Motion, start operating the camera, move with WASD, and press Enter at each shot.'],
    ['Preview and export', 'Check the route, preview the final shot, then export an MP4 reference video.'],
  ],
  cameraShortcuts: 'Camera shortcuts',
  move: 'Move',
  descendAscend: 'Down / Up',
  saveShot: 'Save shot',
  playPause: 'Play / Pause',
  exitCamera: 'Exit camera',
  releaseBadge: 'What is new',
  releaseTitle: 'Improved route editing, monitoring, and export',
  releaseDescription: 'This update strengthens character motion, camera preview, and reference-video workflows.',
  releaseNotes: [
    'Character routes support adding, inserting, deleting, and dragging points with smooth directional changes',
    'Character and camera paths can stay visible, with batch movement for multiple path points',
    'Path collision keeps characters grounded and prevents characters and cameras from crossing scene objects',
    'Final preview supports pausing and timeline scrubbing without leaving the first-person view',
    'Main output FOV and monitor-window FOV are configured separately, and exports use the main output FOV',
    'Includes a draggable live monitor, MP4 reference export, and more reliable undo behavior',
  ],
  controlsBadge: 'Full controls',
  controlsTitle: 'Keyboard, mouse, and trackpad controls',
  controlsDescription: 'Shortcuts are disabled while typing. In camera mode, click the 3D viewport first to lock the pointer.',
  controlGroups: [
    {
      title: 'Director view',
      description: 'For scene layout and route inspection',
      controls: [
        ['W / A / S / D', 'Move forward, left, backward, and right'],
        ['Space / Shift', 'Move up / down'],
        ['Drag left mouse', 'Orbit around the scene'],
        ['Drag right mouse', 'Pan the view center'],
        ['Mouse wheel', 'Move closer to / farther from the scene'],
      ],
    },
    {
      title: 'Camera mode',
      description: 'Record camera-path points with FPS-style controls',
      controls: [
        ['W / A / S / D', 'Move forward, left, backward, and right'],
        ['E / Q', 'Move the camera up / down'],
        ['Move mouse', 'Turn the camera'],
        ['Enter', 'Save or update the current camera point'],
        ['Space', 'Play / pause character and object motion'],
        ['F', 'Lock or release the target under the reticle'],
        ['Mouse wheel', 'Adjust camera FOV'],
        ['Esc', 'Release the pointer and exit camera control'],
        ['Click viewport', 'Lock the pointer again'],
      ],
    },
    {
      title: 'General editing',
      description: 'Works for scenes, route points, and the timeline',
      controls: [
        ['⌘ / Ctrl + C', 'Copy selected characters or objects'],
        ['⌘ / Ctrl + V', 'Paste and select the new copy'],
        ['⌘ / Ctrl + Z', 'Undo the latest edit or drag'],
        ['Shift + Click', 'Add to / remove from the scene-tree selection'],
        ['Delete / Backspace', 'Delete the selected object'],
        ['Drag XYZ letter', 'Continuously adjust that axis value'],
        ['↑ / ↓', 'Fine-tune a focused XYZ value'],
        ['Drag timeline', 'Pause immediately and seek to a time'],
      ],
    },
  ],
  macTitle: 'macOS trackpad gestures',
  macDescription: 'Based on default MacBook gestures with Secondary Click enabled',
  macGestures: [
    ['Press and drag with one finger', 'Orbit in director view; move directly to turn in camera mode'],
    ['Scroll vertically with two fingers', 'Zoom in director view; adjust camera FOV in camera mode'],
    ['Secondary-click and drag', 'Pan the director view when macOS Secondary Click is enabled'],
    ['Scroll the home page', 'Review the full guide and release notes'],
    ['Tap the viewport', 'Lock the pointer again after leaving camera control'],
  ],
  toolsTitle: 'Main interface controls',
  toolGroups: [
    ['Top bar', 'Home, desk switcher, director/first-person view, camera workspace, and view sensitivity'],
    ['Viewport toolbar', 'Move, rotate, scale, add characters, keep routes visible, import models, model library, and add cameras'],
    ['Frame tools', 'Aspect ratio, current/four-way/twelve-way screenshots, and fullscreen'],
    ['Timeline', 'Return to start, play/pause, scrub, duration, recorded points, and delete current point'],
    ['Camera workspace', 'Start camera control, add/insert/batch-move points, preview route/final shot, and export video'],
    ['Inspector', 'Object XYZ, pose, action, character route, scene ground, and path collision'],
  ],
  deleteTitle: 'Delete this director desk?',
  deleteDescription: (name: string) => `“${name}” and its locally saved scene data will be permanently deleted. This cannot be undone.`,
  cancel: 'Cancel',
  delete: 'Delete',
  home: 'Home',
  backHome: 'Back to home',
  deskSelector: 'Director desk selector',
  selectDesk: 'Select a director desk',
  create: 'New',
  justUpdated: 'Updated just now',
  minutesAgo: (value: number) => `${value} min ago`,
  hoursAgo: (value: number) => `${value} hr ago`,
} as const

export const directorHomeCopy = {
  'zh-CN': zhCN,
  'en-US': enUS,
} satisfies Record<SupportedLanguage, typeof zhCN | typeof enUS>

